# mypy: ignore-errors
# ruff: noqa: INP001
"""admins and sessions.

Revision ID: 751bdc2406af
Revises:
Create Date: 2025-11-16 23:15:08.548365

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_trigger import PGTrigger

# revision identifiers, used by Alembic.
revision: str = "751bdc2406af"
down_revision: str | None = "feb115297fc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column(
            "id", sa.BigInteger(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "is_superadmin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__admins")),
    )
    op.create_index(
        op.f("ix__admins__username"), "admins", ["username"], unique=True
    )
    op.create_table(
        "sessions",
        sa.Column(
            "id", sa.BigInteger(), sa.Identity(always=False), nullable=False
        ),
        sa.Column(
            "token",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("admin_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admins.id"],
            name=op.f("fk__sessions__admin_id__admins"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__sessions")),
        sa.UniqueConstraint("token", name=op.f("uq__sessions__token")),
    )
    op.create_index(
        op.f("ix__sessions__admin_id"), "sessions", ["admin_id"], unique=False
    )

    core_admins_update_admins_updated_at = PGTrigger(
        schema="core",
        signature="update_admins_updated_at",
        on_entity="core.admins",
        is_constraint=False,
        definition="BEFORE UPDATE ON admins\nFOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    )
    op.create_entity(core_admins_update_admins_updated_at)

    core_sessions_update_sessions_updated_at = PGTrigger(
        schema="core",
        signature="update_sessions_updated_at",
        on_entity="core.sessions",
        is_constraint=False,
        definition="BEFORE UPDATE ON sessions\nFOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    )
    op.create_entity(core_sessions_update_sessions_updated_at)


def downgrade() -> None:
    core_sessions_update_sessions_updated_at = PGTrigger(
        schema="core",
        signature="update_sessions_updated_at",
        on_entity="core.sessions",
        is_constraint=False,
        definition="BEFORE UPDATE ON sessions\nFOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    )
    op.drop_entity(core_sessions_update_sessions_updated_at)

    core_admins_update_admins_updated_at = PGTrigger(
        schema="core",
        signature="update_admins_updated_at",
        on_entity="core.admins",
        is_constraint=False,
        definition="BEFORE UPDATE ON admins\nFOR EACH ROW EXECUTE FUNCTION update_updated_at_column()",
    )
    op.drop_entity(core_admins_update_admins_updated_at)

    op.drop_index(op.f("ix__sessions__admin_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix__admins__username"), table_name="admins")
    op.drop_table("admins")
